["github.com/adrg/xdg"]
  sumVersion = "v0.4.0"
  ["github.com/adrg/xdg".fetch]
    type = "git"
    url = "https://github.com/adrg/xdg"
    rev = "4ec40e24f0cf1039f93c773f2984decdea9719b5"
    sha256 = "1xbkb8wmr6phj2ppr75akc58jdzrv20gc3mkxa1mmb968isy8s6c"

["github.com/alecthomas/chroma"]
  sumVersion = "v0.10.0"
  ["github.com/alecthomas/chroma".fetch]
    type = "git"
    url = "https://github.com/alecthomas/chroma"
    rev = "36bdd4b98823bd1d7be96767cde3dd575e60b406"
    sha256 = "0hjzb61m5lzx95xss82wil9s8f9hbw1zb3jj73ljfwkq5lqk76zq"

["github.com/alecthomas/chroma/v2"]
  sumVersion = "v2.5.0"
  ["github.com/alecthomas/chroma/v2".fetch]
    type = "git"
    url = "https://github.com/alecthomas/chroma"
    rev = "4bfa1bbb7c2d8d8737f1ef9b87c0a3f63ae014f2"
    sha256 = "1wjkpshq3301wc41v23118fjbik169wqbcnz6rxixalxg53a3vss"

["github.com/alessio/shellescape"]
  sumVersion = "v1.4.1"
  ["github.com/alessio/shellescape".fetch]
    type = "git"
    url = "https://github.com/alessio/shellescape"
    rev = "be0896646a3f2d59dc1de4d149beb07c5b2c25c0"
    sha256 = "14zypi8qdxl77lks5b9jshr17idrm4sri1rxgpw5q4dys1palddd"

["github.com/alexflint/go-arg"]
  sumVersion = "v1.4.3"
  ["github.com/alexflint/go-arg".fetch]
    type = "git"
    url = "https://github.com/alexflint/go-arg"
    rev = "f0f44b65d1179ccedb4c56f493f97ec569a6654e"
    sha256 = "1ca7l6kf2v203pmh2jscdm0hp9rg3zfy8k5jnf9y9ga9pkxfhmvs"

["github.com/alexflint/go-scalar"]
  sumVersion = "v1.1.0"
  ["github.com/alexflint/go-scalar".fetch]
    type = "git"
    url = "https://github.com/alexflint/go-scalar"
    rev = "fd60e966956efb1720cbfbf449fb55971209b2db"
    sha256 = "1996wynw6xl99q1glciqckddncclp9hzp2jdvl6d1vw41svc4z2z"

["github.com/andybalholm/brotli"]
  sumVersion = "v1.0.4"
  ["github.com/andybalholm/brotli".fetch]
    type = "git"
    url = "https://github.com/andybalholm/brotli"
    rev = "1d750214c25205863625bb3eb8190a51b2cef26d"
    sha256 = "1zvmj7gbnkq9xwv1bvcxk9acxl06y902148qwbd2kqwgs52wy2c0"

["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.1"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
    sha256 = "0hka6hmyvp701adzag2g26cxdj47g21x6jz4sc6jjz1mn59d474y"

["github.com/dlclark/regexp2"]
  sumVersion = "v1.4.0"
  ["github.com/dlclark/regexp2".fetch]
    type = "git"
    url = "https://github.com/dlclark/regexp2"
    rev = "955551b554999d8e80dba0184eab21e642786508"
    sha256 = "1irfv89b7lfkn7k3zgx610ssil6k61qs1wjj31kvqpxb3pdx4kry"

["github.com/doronbehar/magicmime"]
  sumVersion = "v0.1.1-0.20211127135329-3de4ff29dc49"
  ["github.com/doronbehar/magicmime".fetch]
    type = "git"
    url = "https://github.com/doronbehar/magicmime"
    rev = "3de4ff29dc49ea8f07b0c361193d3137b9c2c6db"
    sha256 = "1llga0pspaghlywvcniw97m2nh1742i7a7gayw92518bmjx0zk56"

["github.com/dsnet/compress"]
  sumVersion = "v0.0.2-0.20210315054119-f66993602bf5"
  ["github.com/dsnet/compress".fetch]
    type = "git"
    url = "https://github.com/dsnet/compress"
    rev = "f66993602bf5da07ef49d35b08e7264ae9fe2b6e"
    sha256 = "15acshlr2h2gl7q114f600h4d3mld5x4zj1hiygaxlv1pfvmz8sz"

["github.com/dsnet/golib"]
  sumVersion = "v0.0.0-20171103203638-1ea166775780"
  ["github.com/dsnet/golib".fetch]
    type = "git"
    url = "https://github.com/dsnet/golib"
    rev = "1ea1667757804fdcccc5a1810e09aba618885ac2"
    sha256 = "1pm5wkiyh8cilyrrw310ygyj3sdb2831aizym2cgs62aaa3iqrvc"

["github.com/dustin/go-humanize"]
  sumVersion = "v1.0.0"
  ["github.com/dustin/go-humanize".fetch]
    type = "git"
    url = "https://github.com/dustin/go-humanize"
    rev = "9f541cc9db5d55bce703bd99987c9d5cb8eea45e"
    sha256 = "1kqf1kavdyvjk7f8kx62pnm7fbypn9z1vbf8v2qdh3y7z7a0cbl3"

["github.com/golang/snappy"]
  sumVersion = "v0.0.4"
  ["github.com/golang/snappy".fetch]
    type = "git"
    url = "https://github.com/golang/snappy"
    rev = "544b4180ac705b7605231d4a4550a1acb22a19fe"
    sha256 = "004cw699yz3pdpawhjhpa0y94c4w479nw1rf39zj6h6027kpwv2j"

["github.com/google/go-cmp"]
  sumVersion = "v0.5.5"
  ["github.com/google/go-cmp".fetch]
    type = "git"
    url = "https://github.com/google/go-cmp"
    rev = "8fa37b4dd109f12e42b131e485268768f18bcbf8"
    sha256 = "12fmkdhyv5d4is8s57k78j097zb0phlgnrkqc03agiszxlid69x7"

["github.com/klauspost/compress"]
  sumVersion = "v1.15.0"
  ["github.com/klauspost/compress".fetch]
    type = "git"
    url = "https://github.com/klauspost/compress"
    rev = "3cfb088132fccad51a8acfb2d238db1fb56583fd"
    sha256 = "1b75kzb3vqspbw65zjqmj0waw5jyy6na7aqr6hg8f4d4mmwlbr13"

["github.com/klauspost/cpuid"]
  sumVersion = "v1.2.0"
  ["github.com/klauspost/cpuid".fetch]
    type = "git"
    url = "https://github.com/klauspost/cpuid"
    rev = "e7e905edc00ea8827e58662220139109efea09db"
    sha256 = "0cmyv3rwv5r5iqvvfhbiwp3jsfa40c6xfm42nxbngd5lygjcwwgf"

["github.com/klauspost/pgzip"]
  sumVersion = "v1.2.5"
  ["github.com/klauspost/pgzip".fetch]
    type = "git"
    url = "https://github.com/klauspost/pgzip"
    rev = "52335df0e96fa9c509c6fa2966697620beef6dc3"
    sha256 = "0m66jcsz27076qvi5qzagzlbyd1sdzh6kbf1njj0sswx86026rx3"

["github.com/mholt/archiver/v3"]
  sumVersion = "v3.5.1"
  ["github.com/mholt/archiver/v3".fetch]
    type = "git"
    url = "https://github.com/mholt/archiver"
    rev = "cc194d2e4af2dc09a812aa0ff61adc4813ea6c69"
    sha256 = "1py186hfy4p69wghqmbsyi1r3xvw1nyl55pz8f97a5qhmwxb3mwp"

["github.com/nwaples/rardecode"]
  sumVersion = "v1.1.3"
  ["github.com/nwaples/rardecode".fetch]
    type = "git"
    url = "https://github.com/nwaples/rardecode"
    rev = "434b4a38896d211779c5cc5e5933c9da424a5a21"
    sha256 = "0s00b8a9gppka3yxkxh7z5wy0ahygl8wbb0fbyx2r0rj879a1c2z"

["github.com/pierrec/lz4/v4"]
  sumVersion = "v4.1.14"
  ["github.com/pierrec/lz4/v4".fetch]
    type = "git"
    url = "https://github.com/pierrec/lz4"
    rev = "a5532e5996ee86d17f8ce2694c08fb5bf3c6b471"
    sha256 = "15ln2hja6mn22lv6hirf1hvfavn45avdns081l4w0krzhb9l6hfp"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/sirupsen/logrus"]
  sumVersion = "v1.9.0"
  ["github.com/sirupsen/logrus".fetch]
    type = "git"
    url = "https://github.com/sirupsen/logrus"
    rev = "f8bf7650dccb756cea26edaf9217aab85500fe07"
    sha256 = "12i402dxq5js4npnncg043vx874h6nk4ffn4gswcccxrp6h10ivz"

["github.com/stretchr/objx"]
  sumVersion = "v0.1.0"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "facf9a85c22f48d2f52f2380e4efce1768749a89"
    sha256 = "19ynspzjdynbi85xw06mh8ad5j0qa1vryvxjgvbnyrr8rbm4vd8w"

["github.com/stretchr/testify"]
  sumVersion = "v1.7.0"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "acba37e5db06f0093b465a7d47822bf13644b66c"
    sha256 = "0ixgjsvafr3513pz3r6pmgk074s2dxkll0dadvl25gkf30rkmh10"

["github.com/ulikunitz/xz"]
  sumVersion = "v0.5.10"
  ["github.com/ulikunitz/xz".fetch]
    type = "git"
    url = "https://github.com/ulikunitz/xz"
    rev = "b0e6b5a2af126053b434443f09f8b9678a31f02c"
    sha256 = "07vynk0sh8i8g7x9p9x04dj8wylvxaf8ypbi43yvcv7j6zd63c72"

["github.com/xi2/xz"]
  sumVersion = "v0.0.0-20171230120015-48954b6210f8"
  ["github.com/xi2/xz".fetch]
    type = "git"
    url = "https://github.com/xi2/xz"
    rev = "48954b6210f8d154cb5f8484d3a3e1f83489309e"
    sha256 = "178r0fa2dpzxf0sabs7dn0c8fa7vs87zlxk6spkn374ls9pir7nq"

["golang.org/x/sys"]
  sumVersion = "v0.0.0-20220715151400-c0bba94af5f8"
  ["golang.org/x/sys".fetch]
    type = "git"
    url = "https://go.googlesource.com/sys"
    rev = "c0bba94af5f85fbad9f6dc2e04ed5b8fac9696cf"
    sha256 = "0l55yp8fy2yd18hjxq4w44hrhyz41i64ccz1fnc5z7w8rxypfm3q"

["golang.org/x/xerrors"]
  sumVersion = "v0.0.0-20191204190536-9bdfabe68543"
  ["golang.org/x/xerrors".fetch]
    type = "git"
    url = "https://go.googlesource.com/xerrors"
    rev = "9bdfabe68543c54f90421aeb9a60ef8061b5b544"
    sha256 = "1yjfi1bk9xb81lqn85nnm13zz725wazvrx3b50hx19qmwg7a4b0c"

["gopkg.in/check.v1"]
  sumVersion = "v0.0.0-20161208181325-20d25e280405"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "20d25e2804050c1cd24a7eea1e7a6447dd0e74ec"
    sha256 = "0k1m83ji9l1a7ng8a7v40psbymxasmssbrrhpdv2wl4rhs0nc3np"

["gopkg.in/yaml.v3"]
  sumVersion = "v3.0.0-20200313102051-9f266ea9e77c"
  ["gopkg.in/yaml.v3".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v3"
    rev = "9f266ea9e77c4c7aab4cf02650570e7c7b3031a5"
    sha256 = "1bbai3lzb50m0x2vwsdbagrbhvfylj9k1m32hgbqwldqx4p9ay35"
